language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.1

    # The SDK version used to compile your project
    - android-25

    - extra-android-m2repository
    - extra-google-m2repository   

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - android list target
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
- chmod +x gradlew
